export const serviceCategories = {
  ["Storage"]: [ "clouddirectory", "s3", "backup", "s3-outposts", "s3-control", "launchwizard", "glacier", "ebs", "elasticfilesystem", "fsx", "storagegateway",],
  ["Management and Governance"]: [ "health", "config", "resource-groups", "ssm-contacts", "logs", "servicecatalog", "opsworks-cm", "license-manager", "organizations", "grafana", "monitoring", "cloudformation", "airflow", "compute-optimizer", "proton", "servicequotas", "ssm-incidents", "opsworks", "chatbot", "appconfig", "ssm", "cloudtrail", "batch",],
  ["Security, Identity & Compliance"]: [ "sts", "signer", "wafv2", "acm-pca", "guardduty", "ds", "ram", "inspector", "cloudhsm", "shield", "fms", "networkinsights", "cognito-idp", "kms", "cognito-sync", "sso", "waf", "waf-regional", "networkmanager", "acm", "access-analyzer", "securityhub", "secretsmanager", "iam", "auditmanager", "cognito-identity", "network-firewall",],
  ["Media Services"]: [ "elastictranscoder", "mediaconnect", "nimble", "medialive", "mediapackage", "mediaconvert", "mediatailor", "ivs", "kinesisvideo", "mediastore",],
  ["Database"]: [ "redshift-data", "rds-data", "sdb", "streams", "neptune", "dax", "docdb", "glue", "timestream", "cassandra", "qldb", "rds", "redshift", "databrew", "elasticache", "dynamodb", "dynamodbstreams",],
  ["Developer Tools"]: [ "codestar", "codeguru-reviewer", "xray", "codecommit", "codeartifact", "fis", "codebuild", "cloud9", "codepipeline", "cloudshell", "codedeploy", "codeguru-profiler",],
  ["Containers"]: [ "fargate", "ecs", "eks", "ecr", "ecr-public", ],
  ["Machine Learning"]: [ "models-v2-lex", "sagemaker", "models", "comprehendmedical", "kendra", "forecast", "translate", "macie2", "frauddetector", "rekognition", "machinelearning", "transcribe", "textract", "lex", "lookoutvision", "personalize", "monitron", "polly", "deepracer", "elastic-inference", "macie", "lookoutequipment", "comprehend", "lookoutmetrics", "deeplens",],
  ["Compute"]: [ "autoscaling", "elasticbeanstalk", "serverlessrepo", "lambda", "imagebuilder", "lightsail", "vmimportexport", "application-autoscaling", "autoscaling-plans", "ec2",],
  ["Migration and Transfer"]: [ "servicediscovery", "importexport", "mgn", "snowball", "discovery", "datasync", "dlm", "transfer", "sms", "dms", "snow-device-management",],
  ["Networking and Content Delivery"]: [ "route53-recovery-cluster", "route53-recovery-control-config", "route53-recovery-readiness", "route53domains", "globalaccelerator", "directconnect", "route53resolver", "AWSCloudMap", "apigateway", "vpc", "appmesh", "elasticloadbalancing", "route53", "cloudfront",],
  ["Internet of Things"]: [ "iotevents", "iotthingsgraph", "iotwireless", "iot1click", "iotcore", "iotfleethub", "iotsitewise", "iotdeviceadvisor", "iotanalytics", "iot", "greengrass",],
  ["End User Computing"]: [ "wam", "apprunner", "aps", "appstream2", "workspaces",],
  ["Application Integration"]: [ "schemas", "firehose", "mq", "events", "kafka", "sns", "sqs", "swf", "appflow", "states", "appsync",],
  ["Analytics"]: [ "emr-containers", "marketplacecommerceanalytics", "datapipeline", "quicksight", "kinesisanalytics", "elasticmapreduce", "lakeformation", "es", "cloudsearch", "dataexchange", "kinesis", "athena",],
  ["Customer Engagement"]: [ "profile", "bugbust", "connect", "chime", "support", "ses", "pinpoint", "email"],
  ["AWS Cost Management"]: [ "ce", "application-cost-profiler",],
  ["Front-End Web & Mobile"]: [ "devicefarm", "geo", "amplify",],
  ["VR & AR"]: [ "sumerian",],
  ["Game Tech"]: [ "gamelift",],
  ["Blockchain"]: [ "managedblockchain",],
  ["Cloud Financial Management"]: [ "cur", "finspace",],
  ["Robotics"]: [ "robomaker",],
  ["Business Applications"]: [ "a4b", "workdocs"],
  ["Quantum Technologies"]: [ "braket",],
  ["Other"]:  ["crowdscale-usagelimitservice"]
}